Us 39986 accordion menu mobile
RedTurtle/design-comuni-plone-theme pull request #121
Opened 2023-03-30 13:35 UTC by sabrina-bongiovanni

Aggiunto accordion al sideMenu e modificato gli stili per far apparire il menu anche in modalità mobile

2023-03-31 08:51 UTC, pnicolli requested changes

2023-03-31 08:51 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/SideMenu.jsx
> +                  aria-aria-labelledby="accordion-title-one"
```suggestion
                  aria-labelledby="accordion-title-one"
```

2023-03-31 08:51 UTC, pnicolli commented on theme/ItaliaTheme/Components/_sideMenu.scss
> +  // }
Rimuovere per pulizia

2023-03-31 08:51 UTC, pnicolli commented on theme/ItaliaTheme/Views/_common.scss
> +    }
Essendo specifico del sidemenu, metterei anche questo codice nel file nuovo dedicato al menu

2023-03-31 08:51 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/SideMenu.jsx
> +            <div className="accordion">
In design-react-kit c'è un componente Accordion che dovrebbe già gestire un po' di logica e stili e semplificare un po' il nostro codice. Non lo trovi sulla documentazione ufficiale perché fa parte della versione nuova che stanno sviluppando per il PNRR, ma @SaraBianchi ci ha già litigato. Sara ti taggo per capire se alla fine ha funzionato o ti ha dato problemi.

2023-03-31 10:04 UTC, sabrina-bongiovanni commented
Fixed ✅

2023-03-31 14:27 UTC, pnicolli commented on theme/ItaliaTheme/Views/_common.scss
> +    }
@sabrina-bongiovanni è rimasto questo punto aperto

2023-05-12 16:25 UTC, pnicolli commented
Adesso che ho mergiato la PR per sistemare il calcolo della progressbar, questa ha nuovi conflitti, perché è lo stesso componente.

2023-06-26 10:55 UTC, pnicolli approved these changes

2023-06-26 10:56 UTC, merged