feat: added contact info in officeCard in ServiceView
RedTurtle/design-comuni-plone-theme pull request #137
Opened 2023-04-14 09:13 UTC by sabrina-bongiovanni

2023-04-26 14:03 UTC, pnicolli requested changes

2023-04-26 14:03 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/OfficeCard.jsx
> +          />
```suggestion
          <img
            src={
              office_fo.image_scales?.preview_image[0]?.scales?.preview.download
            }
            alt={office.id}
            loading="lazy"
            decoding="async"
          />
```

Aggiungi queste due righe per ottimizzare le performance del sito

2023-04-26 14:03 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/OfficeCard.jsx
> +            )}
L'indirizzo non è tra i punti di contatto? Mi sembra non ci sia più tra i dati delle UO.

2023-04-26 14:03 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/OfficeCard.jsx
> +                  pdc.pdc_type !== undefined && (
Questo non serve perché se `pdc_type` è undefined, allora è necessariamente già diverso da `'telefono'`

2023-04-26 14:28 UTC, sabrina-bongiovanni commented on src/components/ItaliaTheme/View/Commons/OfficeCard.jsx
> +            )}
Nel CT Servizio a quanto pare il dato della strada arriva direttamente dentro i dati della UO, solo nella vista servizio però.

2023-04-26 14:29 UTC, sabrina-bongiovanni commented on src/components/ItaliaTheme/View/Commons/OfficeCard.jsx
> +          />
Done!

2023-04-26 14:29 UTC, sabrina-bongiovanni commented on src/components/ItaliaTheme/View/Commons/OfficeCard.jsx
> +                  pdc.pdc_type !== undefined && (
Done!

2023-04-28 07:59 UTC, pnicolli approved these changes

2023-04-28 08:00 UTC, merged