fix: empty alt tag + aria-hidden for link in cards
RedTurtle/design-comuni-plone-theme pull request #173
Opened 2023-05-24 07:18 UTC by sabrina-bongiovanni

2023-05-25 08:59 UTC, pnicolli requested changes

2023-05-25 08:59 UTC, pnicolli commented on src/components/ItaliaTheme/View/EventoView/EventoUlterioriInformazioni.jsx
> +    <div>ciao</div>
Ritogli questo e rimetti la roba commentata qui :)

2023-05-26 07:20 UTC, sabrina-bongiovanni commented on src/components/ItaliaTheme/View/EventoView/EventoUlterioriInformazioni.jsx
> +    <div>ciao</div>
Sorry, fatto :)

2023-05-26 08:20 UTC, pnicolli approved these changes

2023-06-01 15:42 UTC, pnicolli approved these changes

2023-06-01 15:43 UTC, merged