feat: added RichText context prop
RedTurtle/design-comuni-plone-theme pull request #178
Opened 2023-05-24 15:46 UTC by SaraBianchi

Aggiunta possibilità di leggere il `context` ovvero il contenuto del CT dove viene inserito RichText e tutti i suoi sottocomponenti, al momento viene utilizzato nel campo Prenota Appuntamento del CT Servizio nel quale ci serve sull'addon io-prenoto poter leggere lo UID del CT Servizio in un suo blocco 

<img width="1513" alt="Screenshot 2023-05-24 alle 17 45 07" src="https://github.com/RedTurtle/design-comuni-plone-theme/assets/43245702/795a99c9-26a3-4d65-8987-22210740a214">

2023-05-26 14:11 UTC, pnicolli requested changes

2023-05-26 14:11 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/RenderBlocks.jsx
> +              context={context}
Qui devi passare `properties={context}`, perché dell'attributo `context` non se ne fa niente un blocco

2023-05-26 14:11 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/RichText.jsx
> +  context = null,
Mettere qui il default a `null` è un po' "a vuoto", ci sta che abbia un default ma lo metterei nel punto più interno. In altri termini qui toglierei il default e lo metterei in `RenderBlocks`. Ti dirò di più, metterei `{}` come default, è un po' più safe dato che i blocchi potenzialmente si aspettano di averlo sempre un contesto e almeno qualsiasi codice che sia `properties.qualcosa` dentro il blocco non si spacca.

2023-05-29 10:34 UTC, SaraBianchi commented
@pnicolli dovrei aver risolto entrambe le osservazione, ho fatto qualche test e vedo che funziona

2023-05-29 12:29 UTC, pnicolli approved these changes

2023-05-29 12:29 UTC, merged