Us42452 calendar dots mobile
RedTurtle/design-comuni-plone-theme pull request #201
Opened 2023-06-12 13:35 UTC by Wagner3UB

https://redturtle.tpondemand.com/restui/board.aspx?#page=userstory/42452

Calendar block arrows fixed

2023-06-13 09:44 UTC, pnicolli requested changes

2023-06-13 09:44 UTC, pnicolli commented on src/components/ItaliaTheme/Blocks/Calendar/Body.jsx
> +      <div onClick={onClick} className={className}>
Questi elementi non sono accessibili se sono div con onClick, la tastiera li ignora. Dovrebbero essere <button type="button">

2023-06-13 09:46 UTC, Wagner3UB commented on src/components/ItaliaTheme/Blocks/Calendar/Body.jsx
> +      <div onClick={onClick} className={className}>
@pnicolli posso provare un aria-role button o preferisci cambiare il div?

2023-06-13 10:28 UTC, Wagner3UB commented on src/components/ItaliaTheme/Blocks/Calendar/Body.jsx
> +      <div onClick={onClick} className={className}>
@pnicolli Vedi si ti convince.

2023-06-16 08:27 UTC, pnicolli commented on src/components/ItaliaTheme/Blocks/Calendar/Body.jsx
> +      <div onClick={onClick} className={className}>
Ok ho visto l'aggiunta di tabIndex e di onKeyPress. C'è un motivo per cui preferisci questa strada? Il button mi sembra più semplice come implementazione, a prima vista

2023-06-16 13:28 UTC, Wagner3UB commented
<img width="511" alt="Schermata 2023-06-16 alle 15 27 16" src="https://github.com/RedTurtle/design-comuni-plone-theme/assets/60133113/2b5fb9c2-7978-49b7-bb52-31479855abcc">
<img width="1359" alt="Schermata 2023-06-16 alle 15 19 06" src="https://github.com/RedTurtle/design-comuni-plone-theme/assets/60133113/81014172-3aee-4596-b392-c8da0447e6c4">

2023-06-16 13:28 UTC, Wagner3UB commented
@pnicolli Done, preparo anche per la v3

2023-06-21 09:38 UTC, Wagner3UB commented
@pnicolli dopo la nostra chiacchiera, tolto 100% delle palline e messo le frecce
<img width="1335" alt="Schermata 2023-06-21 alle 11 36 35" src="https://github.com/RedTurtle/design-comuni-plone-theme/assets/60133113/9d9d4cb0-6ded-47e0-936e-dd73107f3b57">
<img width="539" alt="Schermata 2023-06-21 alle 11 37 48" src="https://github.com/RedTurtle/design-comuni-plone-theme/assets/60133113/e4edce3a-36b4-414d-b8e8-272211d425b2">

2023-06-22 08:24 UTC, pnicolli approved these changes

2023-06-22 08:28 UTC, merged