feat: twitter block errors remanage
RedTurtle/design-comuni-plone-theme pull request #204
Opened 2023-06-14 10:50 UTC by Wagner3UB

https://redturtle.tpondemand.com/entity/42400-sito-in-errore

Condition added when server response is not iterable (map function false)
Condition added when the reduce shows error. Doesn't show the block in the view.

2023-06-14 10:56 UTC, pnicolli requested changes

2023-06-14 10:56 UTC, pnicolli commented on locales/en/LC_MESSAGES/volto.po
> +msgstr ""
Le traduzioni inglesi le metterei, che già un paio di siti multilingua li abbiamo

2023-06-14 10:56 UTC, pnicolli commented on src/components/ItaliaTheme/Blocks/TwitterPosts/Body.jsx
> +  console.log(request);
Togliere il log

2023-06-14 10:56 UTC, pnicolli commented on src/components/ItaliaTheme/Blocks/TwitterPosts/Body.jsx
> +  });
Lo lascerei come prima, senza fare una modifica che a tutti gli effetti non va a cambiare nulla

2023-06-14 10:56 UTC, pnicolli commented on src/components/ItaliaTheme/Blocks/TwitterPosts/Body.jsx
> +        {!twitter_posts.map && (
Cambierei in
`twitter_posts.length > 0`
che è più chiaro

2023-06-14 10:56 UTC, pnicolli commented on src/components/ItaliaTheme/Blocks/TwitterPosts/Body.jsx
> +          {twitter_posts.map &&
Come sopra, userei length per il controllo

2023-06-14 12:39 UTC, mamico commented on src/components/ItaliaTheme/Blocks/TwitterPosts/Body.jsx
> +          {Array.isArray(twitter_posts) &&
questa condition probabilmente va prima di `<Slider` perchè non so come si comporta un non array con l'attributo `.length` e comunque mi pare inutile lo slider se non ci sono dati

2023-06-16 08:01 UTC, pnicolli approved these changes

2023-06-16 08:02 UTC, merged