feat: added accordion to side menu
RedTurtle/design-comuni-plone-theme pull request #231
Opened 2023-06-29 15:39 UTC by sabrina-bongiovanni

2023-06-30 08:12 UTC, pnicolli requested changes

2023-06-30 08:12 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/SideMenu.jsx
> +    setIsNavOpen(true);
Questo va proprio tolto perché sennò è inutile quello 10 righe più su dentro l'if

2023-06-30 08:12 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/SideMenu.jsx
> +    setIsNavOpen(true);
Devi cambiare invece sopra il valore iniziale di questo stato, come fatto per la V3, che ora qui è così:
```jsx
const [isNavOpen, setIsNavOpen] = React.useState(false);
```

E invece deve diventare
```jsx
const [isNavOpen, setIsNavOpen] = React.useState(
  __CLIENT__ ? window.innerWidth >= 992 : false,
);
```

2023-06-30 08:12 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/SideMenu.jsx
> +                  className="accordion-button"
Tutti questi non ci sono sulla v3, ma so anche che i componenti Accordion del kit sono diversi tra le due versioni, quindi ti chiedo conferma che servano, giusto per scrupolo. In caso mandami un link a dove li hai trovati come esempio così vedo anche io la differenza, grazie

2023-07-12 13:58 UTC, pnicolli requested changes

2023-07-12 14:51 UTC, sabrina-bongiovanni commented on theme/ItaliaTheme/Views/_common.scss
> +.row.row-column-border.row-column-menu-left {
Fatto

2023-07-12 15:14 UTC, pnicolli approved these changes

2023-07-12 15:14 UTC, merged