feat: file view custom
RedTurtle/design-comuni-plone-theme pull request #25
Opened 2022-12-13 08:27 UTC by Wagner3UB

New custom layout for FileView component. Module file layout used as model.

[us33487](https://redturtle.tpondemand.com/entity/33487-usability-e-pagine-file-parte-2)

<img width="554" alt="Schermata 2022-12-09 alle 11 55 30" src="https://user-images.githubusercontent.com/60133113/207259049-fdffbcdc-ecb1-4db8-8926-31fa2e6762c2.png">
<img width="836" alt="Schermata 2022-12-09 alle 12 00 13" src="https://user-images.githubusercontent.com/60133113/207259053-d220be33-2b6b-4761-9c77-09d5374dce9c.png">

2022-12-13 16:14 UTC, pnicolli requested changes

2022-12-13 16:14 UTC, pnicolli commented on src/customizations/volto/components/theme/View/FileView.jsx
> +  <Container className="view-wrapper px-4 my-4">
Conviene usare il componente Container importato da `design-react-kit` invece di questo da semantic-ui. Il motivo è che un giorno potremmo non usare più semantic-ui su Volto, mentre per forza useremo sempre il kit design-react perché c'è bootstrap-italia. Ad ogni modo, dovrebbe essere molto molto simile il risultato, dovrebbe essere un cambio semplice.

2022-12-15 09:26 UTC, Wagner3UB commented on src/customizations/volto/components/theme/View/FileView.jsx
> +  <Container className="view-wrapper px-4 my-4">
Cambiato component

2022-12-16 11:59 UTC, pnicolli approved these changes

2022-12-16 11:59 UTC, merged