feat: rimosso link a form contatto, aggiunto link a motore di ricerca del sito
RedTurtle/design-comuni-plone-theme pull request #269
Opened 2023-08-03 13:18 UTC by mamico

2023-08-03 15:11 UTC, pnicolli requested changes

2023-08-03 15:11 UTC, pnicolli commented on src/customizations/volto/components/theme/NotFound/NotFound.jsx
Quando facciamo una customizzazione solitamente mettiamo una o due righe all'inizio come promemoria di quale fosse il motivo della customizzazione, per i posteri. Ti chiederei di aggiungerlo anche qui, per il resto mi sembra ok la PR.

2023-08-03 15:16 UTC, mamico commented on src/customizations/volto/components/theme/NotFound/NotFound.jsx
fatto

2023-08-04 08:04 UTC, pnicolli approved these changes

2023-08-04 08:04 UTC, merged