Us45070 info block theme colors
RedTurtle/design-comuni-plone-theme pull request #289
Opened 2023-08-21 12:42 UTC by Wagner3UB

Block info - Color pallet options

Default: Primary, secondary and light gray

Variables created to make easy set up the colors when needed (theme custom)

<img width="1555" alt="Schermata 2023-08-21 alle 14 41 11" src="https://github.com/RedTurtle/design-comuni-plone-theme/assets/60133113/535012c3-ca94-4da6-994b-d3424c149a7b">

2023-08-21 14:49 UTC, pnicolli requested changes

2023-08-21 14:49 UTC, pnicolli commented on theme/ItaliaTheme/Blocks/_info.scss
> +$terciary-color: $gray-border;
```suggestion
$tertiary-color: $gray-border;
```

2023-08-21 14:49 UTC, pnicolli commented on theme/ItaliaTheme/Blocks/_info.scss
> +      border-color: $terciary-color;
```suggestion
      border-color: $tertiary-color;
```

2023-08-21 14:49 UTC, pnicolli commented on theme/ItaliaTheme/Blocks/_info.scss
> +        background-color: $terciary-color;
```suggestion
        background-color: $tertiary-color;
```

2023-08-21 14:49 UTC, pnicolli commented on theme/ItaliaTheme/Blocks/_info.scss
> +        background-color: $terciary-color;
```suggestion
        background-color: $tertiary-color;
```

2023-08-21 14:49 UTC, pnicolli commented on theme/ItaliaTheme/Blocks/_info.scss
> +          background-color: darken($terciary-color, 10%);
```suggestion
          background-color: darken($tertiary-color, 10%);
```

2023-08-24 08:08 UTC, pnicolli requested changes

2023-08-30 06:58 UTC, giuliaghisini approved these changes

2023-08-30 07:00 UTC, merged