chore: margin-bottom for left and right positions for image equal zero
RedTurtle/design-comuni-plone-theme pull request #292
Opened 2023-08-22 11:50 UTC by Wagner3UB

Margin-bottom set to zero when left or right position chose

2023-08-22 12:04 UTC, Wagner3UB commented
@pnicolli Aggiungo un'informazione che non sono riuscito a verificare: Sulla v2 questo problema non esiste, il margin-bottom viene ignorato e per questo motivo si vede allineato testo-immagine. La cosa più strana è che il codice e il css sono esattamente uguali.

Esempi su V2 e V3
https://v2.io-comune.redturtle.it/pagina-test-wt
https://v3.io-comune.redturtle.it/test-font-types-wagner

2023-08-24 07:42 UTC, pnicolli requested changes

2023-08-24 07:42 UTC, pnicolli commented on src/theme/ItaliaTheme/Blocks/_imageBlock.scss
> +}
Ho testato e funziona ugualmente anche senza il selettore `p`, quindi con solo `.block.image`. Consiglio di metterlo dentro il blocco superiore che è già `.block.image`. A parte questo, va bene la modifica con il margine 0 come hai proposto.

2023-08-24 07:48 UTC, pnicolli approved these changes

2023-08-24 07:49 UTC, merged