Fix: servizio attivo
RedTurtle/design-comuni-plone-theme pull request #31
Opened 2022-12-20 09:47 UTC by Wagner3UB

Added a wrap to allocate all the future chips

2022-12-23 15:30 UTC, pnicolli commented
@Wagner3UB scusami ma testandolo ieri ho trovato un altro problemino: la nuova Chip viene mostrata su tutti i contenuti, mentre andrebbe mostrata solo per quelli di tipo Servizio.

2022-12-23 16:22 UTC, pnicolli requested changes

2022-12-23 16:22 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/PageHeader/PageHeader.jsx
> +  console.log(props);
Rimuovere

2022-12-23 16:25 UTC, Wagner3UB commented on src/components/ItaliaTheme/View/Commons/PageHeader/PageHeader.jsx
> +  console.log(props);
Errore mio, grazie per la segnalazione. L'ho corretto.

2022-12-23 16:41 UTC, pnicolli approved these changes

2022-12-23 16:42 UTC, pnicolli commented
@Wagner3UB direi che ci siamo. Ti restano da risolvere i conflitti per poter fare il merge, poi siamo a posto.

2022-12-27 13:17 UTC, pnicolli approved these changes

2022-12-27 13:17 UTC, merged