fix: focus on selected and default dates
RedTurtle/design-comuni-plone-theme pull request #333
Opened 2023-09-18 15:09 UTC by sabrina-bongiovanni

2023-09-19 12:09 UTC, deodorhunter commented
@sabrina-bongiovanni ora ti tocca anche aggiungere a manina le release notes, c'e' il suo file apposta. Mettilo sotto migliorie con Accessibilita'-quello che hai fatto in maniera molto sintetica, tanto anche gli altri che vedo son molto generici e vaghi.

Se hai problemi di conflitti vediamo poi

2023-09-20 07:06 UTC, deodorhunter requested changes

2023-09-20 07:06 UTC, deodorhunter commented on RELEASE.md
> +- Migliorata accessibilità del calendario nel blocco ricerca Eventi e ricerca Bandi
Sempre solito problema, purtroppo questa release è fuori ora e non possiamo mettere le nostre note qui, tocca risistemare di nuovo, mi dispiace

2023-09-20 08:40 UTC, sabrina-bongiovanni commented on RELEASE.md
> +- Migliorata accessibilità del calendario nel blocco ricerca Eventi e ricerca Bandi
Stiamo giocando a Jumanji praticamente

2023-09-20 09:16 UTC, merged