* fix: i link in modulistica devono far vedere la remoteUrl e non il link
RedTurtle/design-comuni-plone-theme pull request #336
Opened 2023-09-19 08:22 UTC by mamico

see #334

2023-09-19 08:46 UTC, giuliaghisini requested changes

2023-09-19 08:46 UTC, giuliaghisini commented on RELEASE.md
> +
## Versione X.X.X (dd/mm/yyyy)

### Fix
- sistemati gli oggetti link che puntano a file nella Cartella Modulistica

2023-09-19 08:46 UTC, giuliaghisini commented on RELEASE.md
> +
metterei così @mamico

2023-09-19 12:49 UTC, mamico commented on RELEASE.md
> +
fatto.

2023-09-19 14:04 UTC, mamico commented
> @mamico risolvi i conflitti così mergiamo

fatto

2023-09-20 07:00 UTC, giuliaghisini approved these changes

2023-09-20 07:00 UTC, merged