Us 46340 ordinamento risultati ricerca tastiera
RedTurtle/design-comuni-plone-theme pull request #341
Opened 2023-09-19 13:15 UTC by sabrina-bongiovanni

2023-09-19 14:40 UTC, deodorhunter commented
@sabrina-bongiovanni purtroppo Sabri ti tocca rifare di nuovo il release che ci son stati rilasci nel mezzo e non sono piu' valide le entry dove le hai messe, fai una nuova riga e prega, prendi spunto dal template

2023-09-20 07:06 UTC, giuliaghisini requested changes

2023-09-20 07:06 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/ContactsBlock/Edit.jsx
> -                  <Col lg="4" key={subblock.id} className="pb-3">
La classe pb-3 va lasciata perchè nel caso in cui ci siano piu di 3 blocchi e quindi vanno a capo devono rimanere distanziati e non appiccicati

2023-09-20 07:06 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/ContactsBlock/View.jsx
> +            <Row className="justify-content-center">
la classe della row deve rimanere come era, con la condizione sul fatto che ci siano o meno più di 3 blocchi. Se ci sono meno di 3 blocchi questi rimangono centrati, se ce ne sono piu di 3 sono allineati a sinistra

2023-09-20 07:57 UTC, closed without merging