fix: source added and category deleted for rss single card
RedTurtle/design-comuni-plone-theme pull request #384
Opened 2023-10-31 11:30 UTC by Wagner3UB

Feed source name added to single card feed.

2023-10-31 11:53 UTC, giuliaghisini requested changes

2023-10-31 11:53 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/RssBlock/CardWithImageRssTemplate.jsx
> +                      {item?.source?.length > 0 && (
item.categories deve rimanere. 
In più, deve essere mostrata anche la sorgente.
Mostrerei prima la sorgente e poi le categorie.

2023-10-31 11:53 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/RssBlock/CardWithoutImageRssTemplate.jsx
> +                      {item?.source?.length > 0 && (
item.categories deve rimanere.
In più, deve essere mostrata anche la sorgente.
Mostrerei prima la sorgente e poi le categorie.

2023-10-31 13:29 UTC, Wagner3UB commented
@giuliaghisini o lasciato la classe 'category' così mantiene gli stili identici a quelli della vera categoria senza aver bisogno cambiare il css. Cosa ne pensi?

2023-11-02 08:44 UTC, giuliaghisini commented
@Wagner3UB  non va bene messo dove vengono mostrate le categorie, perchè non si possono mescolare due info diverse.
Mettiamo la sorgente sotto al titolo.

2023-11-02 09:31 UTC, Wagner3UB commented
@giuliaghisini Ho spostato dopo il titolo. Questa volta ho cambiato la classe, non sarebbe corretto mantenere "category" se è una cosa completamente diversa a questo punto.

2023-11-02 09:31 UTC, Wagner3UB commented
<img width="666" alt="Screenshot 2023-11-02 at 10 25 41" src="https://github.com/RedTurtle/design-comuni-plone-theme/assets/60133113/fe2ce2c0-9415-49de-a9ee-3ee50e4e4c15">

2023-11-02 09:43 UTC, giuliaghisini approved these changes

2023-11-02 09:43 UTC, merged