chore: split BandoView Text in different components
RedTurtle/design-comuni-plone-theme pull request #391
Opened 2023-11-07 11:56 UTC by SaraBianchi

2023-11-08 11:14 UTC, giuliaghisini requested changes

2023-11-08 11:14 UTC, giuliaghisini commented on src/components/ItaliaTheme/View/BandoView/BandoText.jsx
> -    ),
questo lo lascerei perchè è la 'forma' che deve avere il contenuto per poter essere renderizzato con questo componente

2023-11-09 08:11 UTC, giuliaghisini approved these changes

2023-11-09 09:42 UTC, pnicolli approved these changes

2023-11-09 09:42 UTC, merged