fix: column template + button text color
RedTurtle/design-comuni-plone-theme pull request #408
Opened 2023-11-16 15:48 UTC by sabrina-bongiovanni

2023-11-17 10:52 UTC, deodorhunter requested changes

2023-11-17 10:52 UTC, deodorhunter commented on src/theme/ItaliaTheme/_main.scss
> +      color: $primary-text !important;
Questa modifica mi pare un po' troppo forte qui. Suggerirei di metterlo nel file contenente gli stili per il blocco Search col suo selettore, poiche' si verifica esclusivamente qui il comportamento anomalo. Tutti gli altri bottoni draftjs sono già a posto nei blocchi di testo per quanto ho visto testando.

2023-11-21 14:59 UTC, pnicolli approved these changes

2023-11-21 14:59 UTC, pnicolli commented on RELEASE.md
> +- Nel blocco Search, quando viene selezionata la variazione "Colonna a destra" o "Colonna a sinistra" i blocchi si allineano correttamente, e i bottoni nella testata si vedono correttamente in modali
```suggestion
- Nel blocco Cerca, quando viene selezionata la variazione "Colonna a destra" o "Colonna a sinistra" i blocchi si allineano correttamente, e i bottoni nella testata si vedono correttamente in modalità Edit.
```

2023-11-21 15:00 UTC, merged