Bug 48229 sovrapposizione etichetta card nastro
RedTurtle/design-comuni-plone-theme pull request #409
Opened 2023-11-17 09:48 UTC by sabrina-bongiovanni

2023-11-17 11:56 UTC, deodorhunter requested changes
@sabrina-bongiovanni ti ho lasciato un commentino, magari valutiamo anche con Piero, ma vorrei evitare quando possibile potenziali future rotture di bootstrap=italia e linee guida a cui piace cambiare

2023-11-17 11:56 UTC, deodorhunter commented on src/theme/ItaliaTheme/Blocks/_ribbonCardTemplate.scss
> +      padding-right: 2rem;
Guardando quello che è l'html e le classi associate in bootstrap-italia, probabilmente fare una cosa di questo tipo"
```
.ribbon-card-template {
  .card,
  .card.card-big {
    .dates {
      font-size: 0.8em;
      text-transform: uppercase;
    }

    .etichetta {
      position: absolute;
      max-width: calc(100% - 176px);
      justify-content: inherit;

```
 Il calcolo sulla width è basato sui valori di margine del ribbon e la sua larghezza (48px e 32 px), il posizionamento assoluto a sinistra (48px, che viene mantenuto dalla classe `.card`, e un ulteriore spaziatura aggiunta per simmetria con il ribbon (48px come il suo margine a sx).
Questo perché abbiamo visto come alle card e alle linee guida piaccia cambiare, in questo modo mantieni le spaziature date da bootstrap-italia, che se cambiano cambiano tutte assieme a bump di versione.
Se vuoi definire delle variabili puoi usare queste
```
$ribbon-spacing-h: calc($spacer * 3);
$ribbon-width: calc($spacer * 2);

```
che usano la variabile e i moltiplicatori definiti da bootstrap-italia come qui https://italia.github.io/bootstrap-italia/docs/organizzare-gli-spazi/spaziature.
La somma finale quindi sarebbe 
```
 max-width: calc(100% - $ribbon-spacing-h * 3 - $ribbon-width);
```
Possono esser definite colocate qui, oppure messe e importate dalle site-variables

2023-11-21 15:19 UTC, pnicolli commented on src/theme/ItaliaTheme/Blocks/_ribbonCardTemplate.scss
> +      right: 0px !important;
Un important in questo tema che è la base per tutti dev'essere molto ben giustificato. Non c'è modo di non usarlo?

2024-03-27 15:31 UTC, pnicolli approved these changes

2024-03-27 15:32 UTC, merged