fix: changed layout of readMore component to avoid overlapping
RedTurtle/design-comuni-plone-theme pull request #411
Opened 2023-11-17 16:48 UTC by sabrina-bongiovanni

2023-11-20 14:35 UTC, deodorhunter approved these changes

2023-11-21 15:07 UTC, deodorhunter commented
@sabrina-bongiovanni Aggiorna il release.md anche :)

2023-11-21 15:44 UTC, pnicolli requested changes
Manca release.md

2023-11-21 15:44 UTC, pnicolli commented on src/theme/ItaliaTheme/Blocks/_bandiInEvidenceTemplate.scss
> +        flex-direction: row;
```suggestion
        flex-direction: row;
```

Le altre righe ci sono già: è già flex ed è già allineato a destra, basta la direction

2023-11-23 10:44 UTC, merged