fix: removed pager-link data-element from prev item button in Pagination
RedTurtle/design-comuni-plone-theme pull request #420
Opened 2023-11-24 16:16 UTC by sabrina-bongiovanni

2023-11-24 16:27 UTC, mamico commented on src/components/ItaliaTheme/Pagination/Pagination.jsx
> +    console.log(items);
@sabrina-bongiovanni ti sono rimasti dei console.log da togliere

2023-11-24 16:57 UTC, sabrina-bongiovanni commented on src/components/ItaliaTheme/Pagination/Pagination.jsx
> +    console.log(items);
Hai ragione Mauro, grazie! Rimossi

2023-11-27 16:23 UTC, pnicolli requested changes

2023-11-27 16:23 UTC, pnicolli commented on src/components/ItaliaTheme/Pagination/Pagination.jsx
> +                  isServiceLink={type === 'prevItem' ? '' : isServiceLink}
`isServiceLink` dovrebbe essere un valore booleano
```suggestion
                  isServiceLink={type !== 'prevItem' && isServiceLink}
```

2023-11-28 09:24 UTC, pnicolli approved these changes

2023-11-28 09:24 UTC, merged