fix: v2 - added aria-live and aria-labels for filters in Search page
RedTurtle/design-comuni-plone-theme pull request #473
Opened 2024-01-09 16:12 UTC by sabrina-bongiovanni

2024-01-16 11:59 UTC, pnicolli requested changes
Manca la generazione delle traduzioni nuove

2024-01-16 11:59 UTC, pnicolli commented on src/components/ItaliaTheme/Search/Search.jsx
> +    defaultMessage: '{filterType} filtri attivati',
Cambia filterType con un'altra dicitura come fatto nelle ultime modifiche per la v3

2024-01-16 14:31 UTC, sabrina-bongiovanni commented on src/components/ItaliaTheme/Search/Search.jsx
> +    defaultMessage: '{filterType} filtri attivati',
fatto

2024-01-19 10:01 UTC, pnicolli approved these changes

2024-01-19 10:02 UTC, merged