fix: v2 - added FocusLock for mobile navbar menu
RedTurtle/design-comuni-plone-theme pull request #478
Opened 2024-01-11 10:37 UTC by sabrina-bongiovanni

2024-01-16 11:57 UTC, pnicolli requested changes

2024-01-16 11:57 UTC, pnicolli commented on package-lock.json
Questo file non deve esserci, non so da dove salti fuori ma rimuovilo

2024-01-16 14:24 UTC, sabrina-bongiovanni commented on package-lock.json
Dallo yarn add di react-focus-lock? Boh
Comunque fatto!

2024-01-19 09:57 UTC, pnicolli commented on package-lock.json
No è più strano di così, quel file salta fuori se non viene usato yarn per installare/aggiornare/modificare le dipendenze, ma se viene usato npm.

2024-01-19 10:00 UTC, pnicolli approved these changes

2024-01-19 10:00 UTC, merged