Appearance card in slider template
RedTurtle/design-comuni-plone-theme pull request #512
Opened 2024-02-01 14:12 UTC by giuliaghisini

Nel template 'Slider' del blocco elenco, ora è possibile scegliere un aspetto diverso per gli elementi dello slider.
Il default è quello che c'è sempre stato, in più si può scegliere di mostrare gli elementi nel formato 'Card semplice' o nel formato 'Card con immagine' .
E' anche facile aggiungere nuovi template custom dal config.blocks.listing.variations e modificando la variazione 'slider'

https://github.com/RedTurtle/design-comuni-plone-theme/assets/51911425/0bd604e9-402d-4605-beb9-f62402720902

2024-02-02 10:05 UTC, pnicolli requested changes
Io farei in modo che le card siano tutte alte uguali, quando vengono usate per i listing normali lo fanno e mi sembra migliore. Per il resto mi pare ok.

2024-02-02 11:26 UTC, giuliaghisini commented on src/config/Blocks/ListingOptions/cardWithImageTemplate.js
> +export const imageCardTemplateOptions = (
serve per fare in modo che le opzioni relative alla visualizzazione di ogni singola card, si possano riutilizzare in altri template, dove appunto viene riutilizzato il componente di visualizzazione dell'elemento. 
Metto un commento anche nel codice

2024-02-05 10:49 UTC, giuliaghisini commented
@pnicolli ho anche aggiunto un controllo sul numero di slide da mostrare nel caso in cui questo fosse maggiore del numero di elementi risultanti dalla query, perchè in quel caso si vedevano gli elementi ripetuti nello slider e lo slider si vedeva male

2024-02-05 10:50 UTC, giuliaghisini commented
@pnicolli ho anche splittato il file degli stili del template cardWithImage e inEvidenceTemplate

2024-02-22 15:15 UTC, giuliaghisini commented
@pnicolli ho verificato e sistemato l'accessibilità. 
C'erano in generale dei problemi con la navigazione da tastiera e lo screen-reader. 
Ho creato dei componenti generici per gli slider che sistemano l'accessibilità e li ho usati ovunque vengono fatti degli slider. 
In questo modo abbiamo tutto coerente.

2024-03-07 08:48 UTC, giuliaghisini commented
@pnicolli dovrei avere sistemato tutto, anche i titoli con lo SR nel caso di slider con sole immagini

2024-04-08 10:14 UTC, merged