Simple card title changed from h4 to h3
RedTurtle/design-comuni-plone-theme pull request #514
Opened 2024-02-02 08:50 UTC by Wagner3UB

Due to respect for the HTML hierarchy, the title of the simple card was changed to h3

- RER request - us51097

2024-02-02 09:21 UTC, giuliaghisini approved these changes

2024-02-02 10:08 UTC, pnicolli requested changes
Fare questa modifica va bene per l'accessibilità, ma va ad alterare l'aspetto della card, rendendo il titolo più grande e più grosso. Prova ad aggiungere la classe `h4`, dovrebbe restare visivamente come prima anche se adesso è un h3.

2024-02-02 11:59 UTC, Wagner3UB commented
@pnicolli Hai ragione, fatto 
<img width="853" alt="Screenshot 2024-02-02 at 12 58 57" src="https://github.com/RedTurtle/design-comuni-plone-theme/assets/60133113/e0eb6362-01c5-408f-b202-990973a7f19c">

2024-02-05 13:24 UTC, deodorhunter approved these changes

2024-02-05 13:25 UTC, deodorhunter commented
@Wagner3UB release.md e poi possiamo mergiare

2024-02-05 13:35 UTC, Wagner3UB commented
@deodorhunter fatto. Non pensavo fosse necessario, sry

2024-02-05 14:07 UTC, deodorhunter approved these changes

2024-02-05 15:25 UTC, pnicolli approved these changes

2024-02-05 15:26 UTC, merged