fix: added aria label to icons across ioComune
RedTurtle/design-comuni-plone-theme pull request #557
Opened 2024-02-28 16:05 UTC by sabrina-bongiovanni

Aggiunti alt a tutti gli elementi richiesti da Mauve
So che alcuni alt non verranno mai letti perchè hanno "aria-hidden" =  "true" e perchè sono parte di elementi non leggibili da SR, ma Mauve li segnala comunque

2024-03-25 09:03 UTC, deodorhunter requested changes

2024-03-25 09:03 UTC, deodorhunter commented on src/components/ItaliaTheme/Blocks/Listing/SliderTemplate.jsx
> +      <Icon icon="chevron-right" key="chevron-right" title="sliderNextArrow" />
Non vorrei dire una cavolata ma: vedo che in generale sono misti tra tradotti con intl e title=id a caso. Non sarebbe meglio metterli tutti tradotti? Dovresti avere gia' il 98% dei messaggi, usa quelli degli span visually-hidden o del primo pezzo di testo contiguo che rappresenta la stessa cosa

2024-03-26 16:54 UTC, pnicolli commented
@sabrina-bongiovanni ci sono nuovi conflitti dovuti all'altro aggiornamento sull'aria-hidden delle icone

2024-03-27 14:19 UTC, pnicolli requested changes
C'è un motivo per cui hai preferito `title` a `aria-label`? Per capire di essere allineati sul discorso, perché so che abbiamo discusso entrambe le ipotesi in passato e usato entrambe ma ora usiamo aria-label ovunque a meno che non sia necessario il title per altri motivi.

2024-03-27 14:19 UTC, pnicolli commented on locales/en/LC_MESSAGES/volto.po
Mancano le traduzioni in inglese

2024-03-27 14:19 UTC, pnicolli commented on src/components/ItaliaTheme/Blocks/Accordion/Block/ViewBlock.jsx
> +              title="toggle"
Tradurre il titolo

2024-03-27 14:19 UTC, pnicolli commented on src/components/ItaliaTheme/Blocks/Common/SearchFilters/DateFilter.jsx
> +        customCloseIcon={customCloseIcon()}
Perché non mettere direttamente le icone qui dentro?

Tipo così

```suggestion
        customArrowIcon={
          <Icon
            icon="it-arrow-right"
            color="white"
            title={intl.formatMessage(messages.roleDescription)}
          />
        }
```

O in alternativa se diventa troppo brutto farei almeno in modo che `customArrowIcon` non sia una funzione ma una semplice variabile, tanto non ha realmente dei parametri, cioè non hai bisogno di generarla con una funzione per renderla mutabile in base a certi parametri.

2024-03-27 14:19 UTC, pnicolli commented on src/components/ItaliaTheme/Blocks/Listing/SliderTemplate.jsx
> +                    title={userAutoplay ? 'pause' : 'play'}
Starebbero bene tradotti pause e play se è una cosa veloce

2024-03-27 14:19 UTC, pnicolli commented on src/components/ItaliaTheme/Icons/FontAwesomeIcon.jsx
>        }}
Non hai messo l'`aria-labelledby` in questo

2024-03-27 14:19 UTC, pnicolli commented on src/components/ItaliaTheme/Icons/Icon.jsx
> +  const { icon, className, color, size, padding, title, ...rest } = props;
Come visto per l'altra PR su aria-hidden, questa modifica è ridondante, perché se nelle props hai `title` e non lo estrapoli, quello rimane dentro `rest` e poi `rest` viene spreaddato in `FontAwesomeIcon` quindi è esattamente identico a passargli `title={title}`, quindi puoi ometterlo, non serve scriverlo.

2024-03-27 14:19 UTC, pnicolli commented on src/components/ItaliaTheme/Icons/SectionIcon.jsx
> +const SectionIcon = ({ section, iconProps, title }) => {
Stesso discorso di sopra, è ridondante, viene già passato grazie ad `iconProps`

2024-03-27 14:19 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/HelpBox.jsx
> +          altText={intl.formatMessage(messages.ulteriori_info)}
Meglio `aria-label`?

2024-03-27 14:19 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/LocationItem.jsx
> +          altText={intl.formatMessage(messages.icona_luoghi)}
Meglio `aria-label`?

2024-03-27 14:19 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/OfficeCard.jsx
> +          altText={intl.formatMessage(messages.icona_ufficio)}
Meglio `aria-label`?

2024-03-27 14:19 UTC, pnicolli commented on src/components/ItaliaTheme/View/Commons/SearchSectionForm.jsx
> +            altText={intl.formatMessage(messages.search)}
Meglio `aria-label`?

2024-03-27 14:19 UTC, pnicolli commented on src/components/ItaliaTheme/View/EventoView/EventoContattiOrganizzatoreEsterno.jsx
> +          altText={intl.formatMessage(messages.icona_telefono)}
Meglio `aria-label`?

2024-03-27 14:19 UTC, pnicolli commented on src/components/SelectInput/SelectInput.jsx
> +        altText={intl.formatMessage(messages.dropwdown_indicator)}
Meglio `aria-label`?

2024-03-27 14:19 UTC, pnicolli commented on src/components/SelectInput/SelectInput.jsx
> +          altText={intl.formatMessage(messages.ay11_for_cancel)}
Meglio `aria-label`?

2024-03-27 14:19 UTC, pnicolli commented on src/customizations/volto-form-block/components/Field.jsx
> +        altText={intl.formatMessage(messages.open_menu)}
Meglio `aria-label`?

2024-03-27 16:19 UTC, pnicolli approved these changes

2024-03-27 16:20 UTC, merged