Argomenti in Evidenza - Gestione sfondo, testo e sidebar
RedTurtle/design-comuni-plone-theme pull request #590
Opened 2024-03-15 14:53 UTC by Wagner3UB

[*Vedere sulla US il video-test ](https://redturtle.tpondemand.com/entity/50242-altri-argomenti-in-evidenza)

- rimosso sfondo de non ci sono card
- sidebar sistemata per non avere l'obbligatorietà di avere un card
- Descrizione per info in più sulla sidebar
- Titolo nero se non c'è lo sfondo
- gestione spazi se non ci sono card
- Aggiunte classi per identificazione

2024-03-19 11:01 UTC, pnicolli requested changes
Mi piace. Aggiungerei una cosa, al momento vedo che rimane lo sfondo colorato quando sono in Modifica e non ci sono argomenti selezionati. Farei sparire lo sfondo anche in Modifica quando non ci sono argomenti selezionati, in modo che si comporti in maniera simile alla View.

2024-03-22 10:09 UTC, SaraBianchi commented
@pnicolli @Wagner3UB ho aggiornato la pr come diceva Piero, nascondendo il background se non ci sono card Argomento, inoltre ho aggiunto due prop, una che permette di allineare le chips degli altri argomenti al centro e una seconda che permette di nascondere il pulsante "Vedi tutti" fisso sotto al blocco che punta alla pagina /argomenti, aggiungendoli qui non abbiamo bisogno di customizzare il blocco su Varese, nei nostri attuali io-comune non cambia niente perchè di default sono false.

<img width="1584" alt="Screenshot 2024-03-22 alle 10 46 30" src="https://github.com/RedTurtle/design-comuni-plone-theme/assets/43245702/c3ee96f0-9d81-4d10-85c9-6ccc0e7a8990">

<img width="1584" alt="Screenshot 2024-03-22 alle 10 45 38" src="https://github.com/RedTurtle/design-comuni-plone-theme/assets/43245702/a572437b-3a5e-49c7-95e6-e837bfb04794">

2024-03-25 09:23 UTC, Wagner3UB commented
> @pnicolli @Wagner3UB ho aggiornato la pr come diceva Piero, nascondendo il background se non ci sono card Argomento, inoltre ho aggiunto due prop, una che permette di allineare le chips degli altri argomenti al centro e una seconda che permette di nascondere il pulsante "Vedi tutti" fisso sotto al blocco che punta alla pagina /argomenti, aggiungendoli qui non abbiamo bisogno di customizzare il blocco su Varese, nei nostri attuali io-comune non cambia niente perchè di default sono false.

@pnicolli Vedi se ti convince fare la modifica per centrare gli argomenti su io-Comune. @SaraBianchi non sapeva che era una custom solo per Varese.

2024-03-27 16:25 UTC, pnicolli commented
> > @pnicolli @Wagner3UB ho aggiornato la pr come diceva Piero, nascondendo il background se non ci sono card Argomento, inoltre ho aggiunto due prop, una che permette di allineare le chips degli altri argomenti al centro e una seconda che permette di nascondere il pulsante "Vedi tutti" fisso sotto al blocco che punta alla pagina /argomenti, aggiungendoli qui non abbiamo bisogno di customizzare il blocco su Varese, nei nostri attuali io-comune non cambia niente perchè di default sono false.
> 
> @pnicolli Vedi se ti convince fare la modifica per centrare gli argomenti su io-Comune. @SaraBianchi non sapeva che era una custom solo per Varese.

Mi sta bene metterlo se è un parametro e se il default è false, cioè se il default è che rimane com'è prima.

2024-03-28 12:33 UTC, SaraBianchi commented
> > > @pnicolli @Wagner3UB ho aggiornato la pr come diceva Piero, nascondendo il background se non ci sono card Argomento, inoltre ho aggiunto due prop, una che permette di allineare le chips degli altri argomenti al centro e una seconda che permette di nascondere il pulsante "Vedi tutti" fisso sotto al blocco che punta alla pagina /argomenti, aggiungendoli qui non abbiamo bisogno di customizzare il blocco su Varese, nei nostri attuali io-comune non cambia niente perchè di default sono false.
> > 
> > 
> > @pnicolli Vedi se ti convince fare la modifica per centrare gli argomenti su io-Comune. @SaraBianchi non sapeva che era una custom solo per Varese.
> 
> Mi sta bene metterlo se è un parametro e se il default è false, cioè se il default è che rimane com'è prima.

@pnicolli  Infatti è così, ho sistemato i conflitti, se è tutto ok si può mergiare

2024-04-08 10:21 UTC, pnicolli approved these changes

2024-04-08 10:22 UTC, merged