fix: translated aria-label of menu hamburger icon
RedTurtle/design-comuni-plone-theme pull request #591
Opened 2024-03-15 15:41 UTC by sabrina-bongiovanni

2024-03-15 16:59 UTC, sabrina-bongiovanni commented
Da correggere, non mergiare :) (anche se forse era ovvio guardando il codice :D )

2024-03-19 10:55 UTC, pnicolli requested changes

2024-03-26 16:44 UTC, pnicolli requested changes

2024-03-26 16:44 UTC, pnicolli commented on locales/en/LC_MESSAGES/volto.po
> +msgstr ""
Aggiungi traduzione almeno qui in inglese

2024-03-26 16:44 UTC, pnicolli commented on src/customizations/volto/components/theme/Navigation/Navigation.jsx
> +              action: collapseOpen ? 'Chiudi' : 'Apri',
Ho realizzato solo ora alla terza rilettura della pr che devi tradurre anche le due stringhe "Chiudi" e "Apri", sennò il risultato viene tradotto solo a metà.

2024-03-27 13:26 UTC, sabrina-bongiovanni commented on src/customizations/volto/components/theme/Navigation/Navigation.jsx
> +              action: collapseOpen ? 'Chiudi' : 'Apri',
Fatto

2024-04-02 17:37 UTC, pnicolli commented
@sabrina-bongiovanni occhio che nell'ultimo commit ti sono sfuggiti dentro dei conflitti non risolti

2024-04-03 08:05 UTC, pnicolli approved these changes

2024-04-03 08:05 UTC, merged