fix: added aria-hidden attribute to icons
RedTurtle/design-comuni-plone-theme pull request #595
Opened 2024-03-15 16:51 UTC by sabrina-bongiovanni

2024-03-18 08:43 UTC, giuliaghisini requested changes

2024-03-18 08:43 UTC, giuliaghisini commented on src/components/ItaliaTheme/Icons/FontAwesomeIcon.jsx
> +      aria-hidden={ariaHidden || null}
```suggestion
      aria-hidden={ariaHidden}
```

2024-03-25 15:03 UTC, sabrina-bongiovanni commented on src/components/ItaliaTheme/Icons/FontAwesomeIcon.jsx
> +      aria-hidden={ariaHidden || null}
fatto!

2024-03-25 15:47 UTC, Wagner3UB submitted a review, later dismissed

2024-03-26 16:49 UTC, pnicolli requested changes
Fai anche qui le modifiche suggerite da Martina per v3 (ariaHidden -> aria-hidden)

2024-03-27 12:00 UTC, sabrina-bongiovanni commented
@pnicolli fatto

2024-03-27 14:29 UTC, pnicolli approved these changes

2024-03-27 14:29 UTC, merged