feat: added new AttachmentCardTemplate listing variation
RedTurtle/design-comuni-plone-theme pull request #603
Opened 2024-03-20 16:25 UTC by SaraBianchi

US [50351](https://redturtle.tpondemand.com/entity/50351-blocco-elenco-nuova-variazione-allegati)
Nuova variazione del blocco elenco "Allegati", attraverso l'opzione "Mostra i PDF in anteprima" diamo la possibilità di aprire gli oggetti di tipo file PDF in anteprima in una nuova tab oppure per ogni oggetto di tipo File è possibile scaricarlo.

<img width="1670" alt="Screenshot 2024-03-20 alle 17 02 55" src="https://github.com/RedTurtle/design-comuni-plone-theme/assets/43245702/a990f7fa-4e24-4753-831c-0d390ace8afe">

Per tutti gli altri tipi di oggetto rimane un semplice collegamento

<img width="1670" alt="Screenshot 2024-03-20 alle 17 01 33" src="https://github.com/RedTurtle/design-comuni-plone-theme/assets/43245702/c830908b-2a2e-4afb-8dc9-6a89c7c5f294">

Da mergiare anche sul branch di Slate, dove viene mostrato anche l'info della dimensione e del mime-type

<img width="1669" alt="Screenshot 2024-03-20 alle 16 47 18" src="https://github.com/RedTurtle/design-comuni-plone-theme/assets/43245702/a57dbfc4-502f-4bd3-b737-8fbaa557bb03">

2024-03-21 07:48 UTC, giuliaghisini approved these changes

2024-03-26 09:46 UTC, pnicolli requested changes

2024-03-27 09:10 UTC, SaraBianchi commented on src/components/ItaliaTheme/Blocks/Listing/AttachmentCardTemplate.jsx
> +                    title={intl.formatMessage(messages.attachment)}
Ok consultandomi con Wagner lasciamo solo l'alt

2024-03-27 09:13 UTC, Wagner3UB commented on src/components/ItaliaTheme/Blocks/Listing/AttachmentCardTemplate.jsx
> +                    title={intl.formatMessage(messages.attachment)}
> Servono entrambi? Chiamo in causa anche @Wagner3UB per un parere

Ho sentito Sara in persona ma scrivo anche qui: No, title per un icon non va bene, anche se è un link, il alt-text deve esistere anche se vuoto, in caso di un'immagine decorativa o se c'è un testo che l'ho spiega meglio subito dopo. Evitare anche ridondanza (alt-text + testo del link).

2024-03-27 09:13 UTC, SaraBianchi commented on src/components/ItaliaTheme/Blocks/Listing/AttachmentCardTemplate.jsx
> +            <Col>
Il layout l'ho copiato da tutti gli altri nostri blocchi elenco...SimpleCardTemplateCompact, AmministrazioneTraspatenteTemplate, BandiInEvidenceTemplete ecc sono tutti fatti così.
Lo tolgo dal mio template ma dovremmo fare anche un po' di pulizia.

2024-03-27 09:30 UTC, SaraBianchi commented on src/components/ItaliaTheme/Blocks/Listing/AttachmentCardTemplate.jsx
> +                    title={intl.formatMessage(messages.attachment)}
Anche qui ci sarebbe da fare pulizia perchè molte Icon su io-comune sono fatte in questo modo.

2024-03-27 15:08 UTC, pnicolli commented on src/components/ItaliaTheme/Blocks/Listing/AttachmentCardTemplate.jsx
> +            <Col>
Corretto

2024-03-27 15:14 UTC, pnicolli approved these changes

2024-03-27 15:16 UTC, merged