fix: added role='button' to search link
RedTurtle/design-comuni-plone-theme pull request #612
Opened 2024-03-26 15:12 UTC by sabrina-bongiovanni

2024-03-26 16:38 UTC, pnicolli requested changes

2024-03-26 16:38 UTC, pnicolli commented on src/components/ItaliaTheme/Header/HeaderSearch/HeaderSearch.jsx
>            href="#search"
```suggestion
          href="/search"
```
Vedi spiegazione nell'altra PR

2024-03-27 11:31 UTC, sabrina-bongiovanni commented on src/components/ItaliaTheme/Header/HeaderSearch/HeaderSearch.jsx
>            href="#search"
Fatto!

2024-03-27 14:35 UTC, pnicolli approved these changes

2024-03-27 14:35 UTC, pnicolli approved these changes

2024-03-27 14:35 UTC, merged