fix: added aria-label for cardReadMore component in iconBlock
RedTurtle/design-comuni-plone-theme pull request #618
Opened 2024-03-27 14:10 UTC by sabrina-bongiovanni

Non ho aggiornato il release.md perchè c'è già un'altra pr che aggiunge l'info sulle migliorie all'accessibilità di del blocco icone

2024-03-27 14:16 UTC, sabrina-bongiovanni commented
@Wagner3UB

2024-03-27 14:23 UTC, deodorhunter requested changes

2024-03-27 14:23 UTC, deodorhunter commented on src/components/ItaliaTheme/Blocks/IconBlocks/Block/ViewBlock.jsx
> +                : intl.formatMessage(messages.vedi) + ' ' + data.title
```suggestion
                : `${intl.formatMessage(messages.vedi)}${data.title ? ` ${data.title}` : ''}`
```
Vedendo sopra data.title non è scontato ci sia sempre

2024-03-27 15:05 UTC, pnicolli requested changes

2024-03-27 15:05 UTC, pnicolli commented on src/components/ItaliaTheme/Blocks/IconBlocks/Block/ViewBlock.jsx
> +                : intl.formatMessage(messages.vedi) + ' ' + data.title
Vero, inoltre renderizzare il title si fa con redraft come sopra alla riga 46

```jsx
            {redraft(
              data.title,
              config.settings.richtextViewSettings.ToHTMLRenderers,
              config.settings.richtextViewSettings.ToHTMLOptions,
            )}
```

Farei inoltre come suggerisce giulia nella descrizione del ticket, cioè il data.title ce lo metterei sempre
```jsx
aria-label={`${data.linkMoreTitle || intl.formatMessage(messages.vedi)} ${data.title ? redraft(...) : ''}`}
```

2024-03-28 15:34 UTC, sabrina-bongiovanni commented
@deodorhunter @pnicolli 
Ho dovuto creare una stringa creando un renderer per redraft ad hoc per estrarre una semplice stringa, i renderer di ioComune producono un elemento html che dentro l'aria label non va bene
Testandolo in locale con anche più di una card nel blocco non dà problemi, tutte le aria-label si costruiscono nella maniera corretta

2024-04-08 10:34 UTC, pnicolli approved these changes

2024-04-08 10:35 UTC, merged