fix: prevent xss in form block reading sent data from BE response
RedTurtle/design-comuni-plone-theme pull request #651
Opened 2024-04-12 12:32 UTC by giuliaghisini

instead reading from current compile state.

2024-04-18 07:46 UTC, giuliaghisini commented
@pnicolli

2024-04-18 07:46 UTC, giuliaghisini commented
gia messo in dcpt 12.0.x

2024-05-10 10:47 UTC, pnicolli requested changes

2024-05-10 10:47 UTC, pnicolli commented on src/customizations/volto-form-block/components/FormResult.jsx
Serve un commento che spiega in breve perché è customizzato o cosa è stato customizzato in questo file

2024-05-20 10:36 UTC, pnicolli approved these changes

2024-05-20 10:43 UTC, merged