fix: accessibility fixes for mauve
RedTurtle/design-comuni-plone-theme pull request #679
Opened 2024-05-15 10:13 UTC by sabrina-bongiovanni

2024-05-15 15:43 UTC, pnicolli requested changes

2024-05-15 15:43 UTC, pnicolli commented on src/customizations/volto/components/manage/Blocks/Search/components/DateRangeFacet.jsx
> +            customCloseIcon={CloseIcon(props)}
Preferirei la sintassi tradizionale con jsx del tipo `<CloseIcon intl={intl} />` oppure `<CloseIcon {...props} />`, che è quella che usiamo solitamente

2024-05-15 15:43 UTC, pnicolli commented on src/components/ItaliaTheme/Blocks/IconBlocks/Block/ViewBlock.jsx
> +            <Icon icon={data.icon} aria-hidden={true} title={cardTitle} />
Meglio aria-label rispetto a title? Mi sembra abbiamo fatto così con tutte le altre icone

2024-05-15 15:43 UTC, pnicolli commented on src/components/ItaliaTheme/View/ServizioView/ServizioCondizioni.jsx
> +              title={intl.formatMessage(messages.condizioni_link)}
Anche qui forse meglio aria-label

2024-05-15 15:43 UTC, pnicolli commented on src/customizations/volto/components/manage/Blocks/Search/components/DateRangeFacet.jsx
> +  },
Forse manca un giro di `yarn i18n`? Mi sembra di non aver visto questo nei file .po

2024-05-15 15:51 UTC, sabrina-bongiovanni commented on src/components/ItaliaTheme/Blocks/IconBlocks/Block/ViewBlock.jsx
> +            <Icon icon={data.icon} aria-hidden={true} title={cardTitle} />
Per tutte le icon abbiamo usato title, perchè va a inserire il tag title con l'id corrispondente a aria-labelledby

<img width="459" alt="image" src="https://github.com/RedTurtle/design-comuni-plone-theme/assets/116291154/96a37824-a7e5-4544-aedf-c1b0fda474bd">

2024-05-15 15:57 UTC, sabrina-bongiovanni commented on src/customizations/volto/components/manage/Blocks/Search/components/DateRangeFacet.jsx
> +  },
Non l'avevo messo nell'overrideTranslations, non mi ero accorta fosse una customization

2024-05-15 15:57 UTC, sabrina-bongiovanni commented on src/customizations/volto/components/manage/Blocks/Search/components/DateRangeFacet.jsx
> +            customCloseIcon={CloseIcon(props)}
Fatto

2024-05-20 10:14 UTC, pnicolli commented on src/components/ItaliaTheme/Blocks/IconBlocks/Block/ViewBlock.jsx
> +            <Icon icon={data.icon} aria-hidden={true} title={cardTitle} />
Hai ragione, sorry, avevo dimenticato, va bene title

2024-05-20 10:16 UTC, pnicolli approved these changes

2024-05-20 10:24 UTC, merged