feat: added form state warning
RedTurtle/design-comuni-plone-theme pull request #710
Opened 2024-06-25 10:20 UTC by sabrina-bongiovanni

Da mergiare quando si rilascia questa:

https://github.com/collective/volto-form-block/pull/106

2024-07-10 09:53 UTC, pnicolli commented
Convertito a draft in attesa di nuove lavorazioni per integrare le modifiche di https://github.com/collective/volto-form-block/pull/106 come customizzazioni in questo branch

2024-08-21 10:29 UTC, eikichi18 commented
bloccata dal merge di questa PR: https://github.com/RedTurtle/design.plone.policy/pull/68

2024-09-04 16:59 UTC, pnicolli requested changes

2024-09-04 16:59 UTC, pnicolli commented on src/customizations/volto-form-block/components/FormResult.jsx
Manca di spiegare l'aggiunta della nuova customizzazione nel commento in cima

2024-09-04 16:59 UTC, pnicolli commented on src/customizations/volto-form-block/components/Sidebar.css
Non ho capito perché hai customizzato questo file. Se è perché l'import in `Sidebar.jsx` è relativo, allora piuttosto cambia come è fatto l'import

2024-09-04 16:59 UTC, pnicolli commented on src/customizations/volto-form-block/components/Sidebar.jsx
> +import './Sidebar.css';
Nel commento al file css sopra mi riferisco a questo import che può diventare così

```suggestion
import 'volto-form-block/components/Sidebar.css';
```

2024-09-04 16:59 UTC, pnicolli commented on src/customizations/volto-form-block/components/View.jsx
Manca la descrizione di cosa è stato customizzato

2024-09-04 16:59 UTC, pnicolli commented on src/customizations/volto-form-block/fieldSchema.js
Manca la descrizione di cosa è stato customizzato

2024-09-04 16:59 UTC, pnicolli commented on src/customizations/volto-form-block/formSchema.js
Manca la descrizione di cosa è stato customizzato

2024-09-05 12:49 UTC, pnicolli approved these changes

2024-09-05 12:57 UTC, merged