feat: added date fields to view
RedTurtle/design-comuni-plone-theme pull request #711
Opened 2024-06-25 15:16 UTC by sabrina-bongiovanni

2024-07-03 08:18 UTC, pnicolli requested changes

2024-07-03 08:18 UTC, pnicolli commented on src/components/ItaliaTheme/View/IncaricoView/IncaricoView.jsx
> +import moment from 'moment';
Di questo bisogna fare lazy loading. Cerca `injectLazyLibs` per trovare un esempio

2024-07-04 08:24 UTC, sabrina-bongiovanni commented on src/components/ItaliaTheme/View/IncaricoView/IncaricoView.jsx
> +import moment from 'moment';
fatto!

2024-07-10 09:47 UTC, pnicolli approved these changes

2024-07-10 09:52 UTC, merged