feat: add pagination to cards listings in Venue, refactor pagination logic into custom hook
RedTurtle/design-comuni-plone-theme pull request #726
Opened 2024-07-17 14:34 UTC by deodorhunter

- Aggiunta la paginazione per le card presenti sotto i campi "Sede di" e "Servizi presenti nel luogo", ora verranno mostrati solo 4 elementi alla volta
- Rifatorizzato il codice presente gia' in UOServices e messo in un hook ts custom, visto che e' una richiesta di recente ricorrente, ora e' comodamente usabile con 
```
interface usePaginatedCardsSectionProps {
  data: Array<any> | null | undefined;
  bSize?: number;
}
Return values:
{
    batches: any[];
    currentPage: number;
    onPaginationChange: (_e: MouseEvent | KeyboardEvent, { activePage }: PaginationFunctionExtraArgs) => void;
    pageNumbers: number;
}

....
usage
...

const { batches, currentPage, onPaginationChange, pageNumbers } =
    usePaginatedCardsSection({ data: servizi_offerti });
    
```
- Il default per bsize è 4, definito in una costante esportata

2024-07-18 07:13 UTC, giuliaghisini requested changes

2024-07-18 07:13 UTC, giuliaghisini commented on src/helpers/usePaginatedCardsSection.hook.ts
> +export function usePaginatedCardsSection({
rendiamoli generici questi hook
chiamiamolo ad esempio 'usePaginatedItemsSection

2024-07-18 07:13 UTC, giuliaghisini commented on src/helpers/usePaginatedCardsSection.hook.ts
> +function divideServicesIntoBatches(
rendiamoli generici questi nomi di funzione.
questo potrebbe essere "divideIntoBatches", oppure "getBatches"

2024-07-18 12:54 UTC, deodorhunter commented on src/helpers/usePaginatedCardsSection.hook.ts
> +export function usePaginatedCardsSection({
Hai ragione, procedo

2024-07-18 12:55 UTC, deodorhunter commented on src/helpers/usePaginatedCardsSection.hook.ts
> +function divideServicesIntoBatches(
Come sopra, qui dimenticato di cambiarlo da copincolla

2024-07-19 10:26 UTC, pnicolli approved these changes

2024-07-19 10:27 UTC, merged