fix: set height to the gallery inside news
RedTurtle/design-comuni-plone-theme pull request #742
Opened 2024-08-13 13:20 UTC by Wagner3UB

Ho impostato una altezza per gli slide della galleria dentro CT notizia come discorso con Sara.

Creato un'alternativa per quando ci sono solo 1 immagine da mostrare.

Verificato su mobile

https://redturtle.tpondemand.com/entity/57799-allineamento-didascalia-in-gallery-foto

<img width="1218" alt="Schermata 2024-08-13 alle 15 17 53" src="https://github.com/user-attachments/assets/ba7dd23f-6436-49e0-b434-5a5ec01b13f6">
<img width="1157" alt="Schermata 2024-08-13 alle 15 18 07" src="https://github.com/user-attachments/assets/6b164247-34d9-4bc9-8f74-582c626dec5c">

2024-08-14 07:16 UTC, giuliaghisini requested changes

2024-08-14 07:16 UTC, giuliaghisini commented on theme/ItaliaTheme/Views/_notizia.scss
> +.contenttype-news-item {
occhio che la gallery nn c'è solo nelle notizie ma anche in altri ct. 
Guarda dove è usato il componente che disegna la gallery per capire in quali ct viene usato. 
Mettiamo il fix per tutti i ct

2024-08-23 07:25 UTC, giuliaghisini requested changes

2024-08-23 07:25 UTC, giuliaghisini commented on theme/ItaliaTheme/Views/_common.scss
> +.contenttype-venue {
non mettiamo le classi specifiche per content-type.
Abbiamo detto di farlo generico 
come selettore, trova una classe del wrapper delle gallery che sia comune a tutte le viste..

2024-08-23 07:25 UTC, giuliaghisini commented on theme/ItaliaTheme/Views/_common.scss
> +.contenttype-venue {
altra cosa: mi sembra che per le regole scritte così per l'evento non funziona, l'hai provato?

2024-08-23 08:38 UTC, Wagner3UB commented on theme/ItaliaTheme/Views/_common.scss
> +.contenttype-venue {
@giuliaghisini avevo capito male io, adesso ho messo un ID che viene usato solo dentro i CT per i contenuto principale, così saremo al sicuro che le classi vengono utilizzate solo dentro i CT.

2024-08-23 09:55 UTC, giuliaghisini approved these changes

2024-08-26 12:40 UTC, merged