fix: video gallery
RedTurtle/design-comuni-plone-theme pull request #747
Opened 2024-08-23 14:43 UTC by Wagner3UB

Cambiata label per la didascalia video
Aggiunto checkbox per mostrare o meno la didascalia

https://redturtle.tpondemand.com/entity/57952-gallery-video

2024-08-27 09:32 UTC, SaraBianchi commented
> Cambiata label per la didascalia video Aggiunto checkbox per mostrare o meno la didascalia
> 
> https://redturtle.tpondemand.com/entity/57952-gallery-video

Come hai scritto nel commento per me questa era una feature nuova, andrei a modificare il tag e a scriverlo anche tra le novità del release.log il resto è a posto

2024-08-27 12:48 UTC, Wagner3UB commented
@SaraBianchi Fatto

2024-09-02 12:30 UTC, Wagner3UB commented
@giuliaghisini Anche questa è da approvare

2024-09-03 07:11 UTC, giuliaghisini requested changes

2024-09-03 07:11 UTC, giuliaghisini commented on RELEASE.md
> +- Aggiunto opzione per la didascalia per il blocco galleria video
```suggestion
- Aggiunta una opzione scegliere se mostrare la didascalia nel blocco Video Gallery
```

2024-09-03 07:11 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx
> +                )}
```suggestion
                
```

2024-09-03 07:11 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx
> +                )}
```suggestion
            
```

2024-09-03 07:11 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx
> +                )}
```suggestion
             
```

2024-09-03 07:11 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx
> +                    )}
```suggestion
                    
```

2024-09-03 07:11 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx
>                  )}
```suggestion
                )}
                
                {showVideoCaption && (
                  <p className="px-3 mt-2 figure-caption">{data.title}</p>
                )}
```

2024-09-04 07:08 UTC, giuliaghisini commented
> @giuliaghisini il corretto, allora, è lasciare la condizione solo a chi ha `data.allowExternals`, giusto?

no, quello non centra nulla con la caption del video

2024-09-04 07:10 UTC, giuliaghisini requested changes

2024-09-04 07:10 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx
> +                  </>
```suggestion
                    <Embed url={data.url} {...embedSettings} />                    
```

ok, ho capito cosa intendevi

2024-09-04 07:45 UTC, Wagner3UB commented
@giuliaghisini dovrebbe essere ok adesso, riesci a fare una ulteriore verifica, per favore?

2024-09-04 08:35 UTC, giuliaghisini approved these changes

2024-09-04 08:35 UTC, merged