feat: Last modified document
RedTurtle/design-comuni-plone-theme pull request #749
Opened 2024-08-28 09:00 UTC by Wagner3UB

Aggiunto data di modifica dentro attachment.jsx per mostrare la data dentro i documenti allegati nei CT Bando

ps: Serve redturtle.bandi aggiornato - Sentire @cekk

2024-08-28 22:29 UTC, SaraBianchi commented
Ricordarsi poi di aggiornare il release.md

2024-09-02 10:53 UTC, Wagner3UB commented
@giuliaghisini Ho modificato il file release.md come richiesto da Sara

2024-09-02 12:09 UTC, giuliaghisini requested changes

2024-09-02 12:09 UTC, giuliaghisini commented on src/components/ItaliaTheme/View/Commons/Attachment.jsx
> +        </p>
```suggestion
       {item?.modified && <p>
          {intl.formatMessage(messages.last_update)}{' '}
          {viewDate(intl.locale, item?.modified, 'DD-MM-Y HH:MM')}
        </p>}
```

2024-09-03 07:04 UTC, giuliaghisini commented
@Wagner3UB attenzione che la richiesta è di mostrare la data di ultima modifica solo per gli allegati del Bando. 
Cosi facendo, in qualsiasi punto del sito venga usato il componente Attachment e gli viene passato il parametro 'item' mostra la data di ultima modifica (se è presente).
Aggiungerei un parametro all componente Attachment del tipo 'showModified' che di default è a false. 
e nel componente del bando che mostra gli attachment va poi passato showModified=true

2024-09-03 07:04 UTC, giuliaghisini requested changes
@Wagner3UB attenzione che la richiesta è di mostrare la data di ultima modifica solo per gli allegati del Bando.
Cosi facendo, in qualsiasi punto del sito venga usato il componente Attachment e gli viene passato il parametro 'item' mostra la data di ultima modifica (se è presente).
Aggiungerei un parametro all componente Attachment del tipo 'showModified' che di default è a false.
e nel componente del bando che mostra gli attachment va poi passato showModified=true

2024-09-03 08:16 UTC, Wagner3UB commented
@giuliaghisini Ok, ho creato una soluzione. Ho messo true solo per i bandi al momento.

2024-09-03 09:36 UTC, giuliaghisini requested changes

2024-09-03 09:36 UTC, giuliaghisini commented on src/components/ItaliaTheme/View/Commons/Attachment.jsx
> +        {showModified && (
```suggestion
        {showModified && item?.modified && (
```

2024-09-04 07:04 UTC, giuliaghisini approved these changes

2024-09-04 07:04 UTC, giuliaghisini commented on RELEASE.md
> +- Aggiunto la data di modifica per mostrare la data dentro i documenti allegati nei CT Bando
```suggestion
- Aggiunto la data di modifica nei documenti allegati del CT Bando
```

2024-09-04 07:05 UTC, merged