fix: custom feedback form title
RedTurtle/design-comuni-plone-theme pull request #752
Opened 2024-08-29 12:26 UTC by mamico

Nelle pratiche il titolo della form di feedback deve essere "quanto ti è stata utile questa pagina" nei vari step e "quanto ti è stato utile questo servizio" solo dopo aver sottomesso la pratica.

Visto che lo stato è gestito nella pratica, viene fatto in modo che feedbackform possa gestire un title custom, rimosso dal footer per alcuni CT il feebackform (ie ModelloPratica), questi ct gestiranno in autonomia la componente FeedbackForm

2024-09-03 08:53 UTC, pnicolli requested changes

2024-09-03 08:53 UTC, pnicolli commented on src/components/ItaliaTheme/CustomerSatisfaction/FeedbackForm.jsx
> +                          : intl.formatMessage(messages.title)} */}
Toglierei il codice vecchio (anche sopra a questo), non c'è chissà quale logica che vale la pena tenere a mente lì

2024-09-03 08:53 UTC, pnicolli commented on src/config/italiaConfig.js
> +      // ['Plone Site', 'LRF', 'Subsite']
Se capisco bene il commento è riportato dal commento rimosso dal Footer. Puoi toglierlo perché era a sua volta un copypaste di un comportamento simile di un altro pezzo del tema. Insomma è inutile :)

2024-09-03 08:53 UTC, pnicolli commented on src/components/ItaliaTheme/CustomerSatisfaction/FeedbackForm.jsx
> +                        {title ? title : intl.formatMessage(messages.title)}
Consiglio addirittura la sintassi ancora più breve `title || intl.formatMessage(...)`

2024-09-03 10:58 UTC, mamico commented on src/components/ItaliaTheme/CustomerSatisfaction/FeedbackForm.jsx
> +                          : intl.formatMessage(messages.title)} */}
Fai tutte le modifiche che hai proposto. Per me sono ok. Thx

2024-09-05 09:35 UTC, pnicolli approved these changes

2024-09-05 09:41 UTC, merged