fix: mobile text not visible
RedTurtle/design-comuni-plone-theme pull request #76
Opened 2023-02-13 13:43 UTC by Wagner3UB

https://redturtle.tpondemand.com/entity/38772-modifica-testo-nella-sezione-di-feedback

The text wasn't visible on mobile screens because of a wrap inside the label. I was necessary to change the distance between text and button when the input receives the focus.

<img width="568" alt="Schermata 2023-02-13 alle 14 38 29" src="https://user-images.githubusercontent.com/60133113/218473031-87f4fbcd-dd63-4370-8d75-ddc29b8b8b80.png">
<img width="572" alt="Schermata 2023-02-13 alle 14 38 33" src="https://user-images.githubusercontent.com/60133113/218473042-33651051-e53c-4021-831a-65882ecd56f8.png">

2023-02-14 14:30 UTC, SaraBianchi approved these changes

2023-02-15 14:13 UTC, pnicolli requested changes

2023-02-15 14:13 UTC, pnicolli commented on theme/ItaliaTheme/Addons/customerSatisfaction.scss
> +    @media (max-width: #{map-get($grid-breakpoints, lg)}) {
```suggestion
    @media (max-width: #{map-get($grid-breakpoints, lg) - 1px}) {
```

Solitamente quando si usa `max-width` è meglio mettere 1px in meno rispetto al breakpoint per non creare sovrapposizioni di stili se lo schermo è largo esattamente come il breakpoint.

2023-02-15 14:13 UTC, pnicolli commented
A me viene così su uno schermo mobile da 375px di larghezza

<img width="350" alt="image" src="https://user-images.githubusercontent.com/14176608/219051217-d09cbc00-83db-484e-af4f-f3eac8765e1e.png">

2023-02-15 16:04 UTC, Wagner3UB commented
@pnicolli ho aggiunto la tua richiesta per il breakpoint, però la questione della sovrapposizione ne ho fatte alcune test e nessuno me risulta come dalla tua immagine.

schermo a 360px
<img width="581" alt="Schermata 2023-02-15 alle 16 36 41" src="https://user-images.githubusercontent.com/60133113/219083320-72d8b31c-4608-42b1-b9c0-b7694aeac398.png">

2023-02-16 09:16 UTC, pnicolli approved these changes

2023-02-16 09:17 UTC, merged