feat: title and description for block accordion - v11
RedTurtle/design-comuni-plone-theme pull request #765
Opened 2024-09-10 12:58 UTC by Wagner3UB

Aggiunti due campi su blocco accordion, uno per il titolo e uno per la descrizione.

tp #50938

2024-09-11 07:25 UTC, giuliaghisini requested changes

2024-09-11 07:25 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/Accordion/Edit.jsx
> +                <div className="description">
a cosa serve questo div? in teoria lo mette gia il widget il div con il nome del campo

2024-09-11 07:25 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/Accordion/Edit.jsx
> +                <TextEditorWidget
hai usato questo widget perchè si vuole poter formattare il titolo con gli stili di draftjs? 
di solito i titoli li mettiamo come testo semplice, ma non so quale fosse la richiesta originale

2024-09-11 08:16 UTC, Wagner3UB commented on src/components/ItaliaTheme/Blocks/Accordion/Edit.jsx
> +                <TextEditorWidget
Chi toglie la toolbar è la prop `showToolbar={false}`

2024-09-11 09:49 UTC, giuliaghisini requested changes

2024-09-11 09:49 UTC, giuliaghisini commented on RELEASE.md
> +- Aggiunto campo per l'inserimento del titolo e della descrizione nel blocco accordion
spostalo nella sezione novità perchè è una cosa nuova

2024-09-12 07:32 UTC, giuliaghisini approved these changes

2024-09-12 07:33 UTC, merged