feat: title and description added to accordion block - v12
RedTurtle/design-comuni-plone-theme pull request #766
Opened 2024-09-10 13:49 UTC by Wagner3UB

Aggiunti due campi su blocco accordion, uno per il titolo e uno per la descrizione.

tp #50938

2024-09-12 07:34 UTC, giuliaghisini approved these changes

2024-09-12 08:00 UTC, pnicolli requested changes
Se hai fatto modifiche dopo la review di Giulia per v11 ricordati di riportarle anche qui

2024-09-12 08:00 UTC, pnicolli commented on src/theme/ItaliaTheme/Blocks/_accordion.scss
> +      }
Non c'è draft qui

2024-09-12 08:00 UTC, pnicolli commented on src/theme/ItaliaTheme/Blocks/_accordion.scss
> +      font-size: 2.35rem !important;
Serve `!important`? Non c'è modo di fare un selettore della specificità giusta?

2024-09-12 09:33 UTC, Wagner3UB commented
> Se hai fatto modifiche dopo la review di Giulia per v11 ricordati di riportarle anche qui

@pnicolli Si, avevo fatto, ma ho riportato tutto qui subito dopo, grazie per l'avviso.

2024-09-12 09:33 UTC, Wagner3UB commented on src/theme/ItaliaTheme/Blocks/_accordion.scss
> +      }
Grazie, questo mi è passato. Rimosso.

2024-09-12 09:34 UTC, Wagner3UB commented on src/theme/ItaliaTheme/Blocks/_accordion.scss
> +      font-size: 2.35rem !important;
Hai ragione, per fortuna su questa versione non si fa necessario. L'ho tolto.

2024-09-17 09:55 UTC, pnicolli approved these changes

2024-09-17 09:55 UTC, merged