feat: new alert block
RedTurtle/design-comuni-plone-theme pull request #795
Opened 2024-10-28 09:13 UTC by Wagner3UB

- Aggiunti campi per compilare la data di inizio e fine per un unico blocco Alert.
- Aggiunto una riga per far vedere le date impostati e se è ATTIVO, SCADUTO o FUTURO, e le date d'inizio e fine se impostati.
- Aggiunto logica per sempre far vedere agli utenti autenticati la riga con le informazioni, anche in View. Le info non si vedono da anonimo.

View autenticato:
![screencapture-localhost-3000-pagina-test-wt-alert-new-block-with-dates-2024-10-28-10_10_32](https://github.com/user-attachments/assets/37ecf256-53e5-4795-ae87-780e83ced3d9)

Edit:
<img width="1728" alt="Schermata 2024-10-28 alle 10 11 17" src="https://github.com/user-attachments/assets/144efb29-005c-4837-891b-0f9701e94a4c">

View anonimo
<img width="1728" alt="Schermata 2024-10-28 alle 10 11 37" src="https://github.com/user-attachments/assets/35321b46-af16-4734-9012-3ce9a30ef216">

2024-10-29 09:38 UTC, giuliaghisini requested changes

2024-10-29 09:38 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/Alert/utils.js
> +import React from 'react';
questo file non credo che serva piu. 
Corretto? 
nel caso va eliminato

2024-10-30 09:22 UTC, SaraBianchi commented on src/components/ItaliaTheme/Blocks/Alert/AlertWrapper.jsx
> +      returnValue.message = intl.formatMessage(messages.expiredDate);
questo possiamo metterlo nel default di returnValue e rimuoviamo una condizione se vogliamo mettere un messaggio sempre. Capiamo un attimo

2024-10-30 16:45 UTC, SaraBianchi approved these changes

2024-10-31 11:50 UTC, giuliaghisini approved these changes

2024-10-31 11:50 UTC, merged