feat: added usePloneRanking option in Search Block
RedTurtle/design-comuni-plone-theme pull request #820
Opened 2024-11-27 10:28 UTC by giuliaghisini

Il comportamento del blocco "Cerca" per l'ordinamento dei risultati è ritornato a funzionare come in origine: ovvero usa l'ordinamento impostato nella sezione dei criteri anche quando un utente effettua una ricerca nel campo 'searchableText'. 

Se si vuole forzare l'ordinamento in base al ranking di Plone quando l'utente effettua una ricerca nel campo 'searchableText', allora è necessario spuntare la nuova opzione "Usa l'ordinamento dei risultati di Plone" presente nella sezione 'Controlli' :

<img width="2050" alt="Screenshot 2024-11-27 alle 11 19 12" src="https://github.com/user-attachments/assets/b4455dd3-8bda-497c-8ead-33bc4d0118a5">

2024-12-03 11:14 UTC, deodorhunter requested changes

2024-12-03 11:14 UTC, deodorhunter commented on RELEASE.md
> +- Nel blocco 'Cerca' è stata aggiunta l'opzione "Usa l'ordinamento dei risultati di Plone" nella sezione 'Controlli'.
Questo e' da spostare nel posto giusto

2024-12-03 11:14 UTC, deodorhunter commented on src/customizations/volto/components/manage/Blocks/Search/schema.js
> +  usePloneRanking: {
Qui non vedo il file delle traduzioni aggiornate, normale?
Per il resto mi torna tutto. avete deciso che e' un cambio di prodotto oppure vi serve solo sul main/slate? Dalla us associata non ho capito, solo per sapere se devo fare cherry-pick o no

2024-12-03 11:39 UTC, giuliaghisini commented on src/customizations/volto/components/manage/Blocks/Search/schema.js
> +  usePloneRanking: {
si si mettiamo a prodotto, cosi ci sono entrambe le possibilità per tutti

2024-12-20 10:43 UTC, pnicolli approved these changes

2024-12-20 10:45 UTC, merged