Bug #39495 carousel close button
RedTurtle/design-comuni-plone-theme pull request #96
Opened 2023-03-20 15:17 UTC by sabrina-bongiovanni

2023-03-20 17:16 UTC, pnicolli requested changes

2023-03-20 17:16 UTC, pnicolli commented on src/components/ItaliaTheme/GalleryPreview/GalleryPreview.jsx
> +                onClick={() => setModalIsOpen(!modalIsOpen)}
Il vecchio header usava la funzione `closeModal`, userei quella anche qui onde evitare problemi imprevisti.

2023-03-22 17:05 UTC, sabrina-bongiovanni commented on src/components/ItaliaTheme/GalleryPreview/GalleryPreview.jsx
> +                onClick={() => setModalIsOpen(!modalIsOpen)}
Risolto!

2023-03-23 15:45 UTC, pnicolli requested changes

2023-03-23 16:02 UTC, pnicolli requested changes

2023-03-23 16:02 UTC, pnicolli commented on src/components/ItaliaTheme/GalleryPreview/GalleryPreview.jsx
> +                onClick={() => setModalIsOpen(!modalIsOpen)}
```suggestion
                onClick={closeModal}
```

2023-03-23 16:02 UTC, pnicolli commented on src/components/ItaliaTheme/GalleryPreview/GalleryPreview.jsx
> +        closeModal();
Annullare questa modifica

2023-03-23 16:33 UTC, pnicolli approved these changes

2023-03-23 16:33 UTC, merged